Add friends likes
DFineev/java-filmorate pull request #9
Opened 2023-06-23 22:32 UTC by DFineev

2023-06-24 19:15 UTC, Yang-Pi requested changes

2023-06-24 19:15 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleIncorrectParameterException(final IncorrectParameterException e) {
Добавь исключений для различных ситуаций, а не объединяй все одним IncorrectParameterException.
Потому что ошибки бывают не только 404, рассмотри еще кейсы для 400 и 500

2023-06-24 19:15 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private HashSet<Integer> likes;
Используй в качестве типа интерфейс Set, а не реализацию HashSet

2023-06-24 19:15 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleIncorrectParameterException(final IncorrectParameterException e) {
<img width="689" alt="image" src="https://github.com/DFineev/java-filmorate/assets/55200686/979fbb63-ae4c-49d8-a269-5168d43f8ce6">

2023-06-27 10:41 UTC, DFineev commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleIncorrectParameterException(final IncorrectParameterException e) {
done

2023-06-28 11:51 UTC, Yang-Pi requested changes

2023-06-28 11:51 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmService filmService = new FilmService(inMemoryFilmStorage);
1) Вот тут стоит использовать подход к инициализации поля класса через аргумент конструктора, это называется "внедрением зависимости" (dependency injection). Мы с тобой это исправляли для класса Managers - как история внедряется в менеджер задач.

2) Так ты нарушаешь правило разделения ответственности - контроллер взаимодействует только с сервисом, который в свою очередь уже может работать с хранилищем.

2023-06-28 11:51 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmService filmService = new FilmService(inMemoryFilmStorage);
Актуально и для другого контроллера

2023-06-30 09:14 UTC, DFineev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmService filmService = new FilmService(inMemoryFilmStorage);
Done

2023-06-30 18:10 UTC, Yang-Pi approved these changes

2023-08-04 19:56 UTC, merged